name: Deploy Nginx to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Add SHORT_SHA env property with commit short sha
        id: image-tag
        shell: bash
        run: |
          echo "IMAGE_TAG=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "image-tag=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT
      
      - name: Bring image from step
        shell: bash
        run: |
          echo "Image tag got is ${{ steps.image-tag.outputs.image-tag }}"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest ${{ secrets.DOCKER_USERNAME }}/my-nginx:${{ env.IMAGE_TAG }}

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/my-nginx:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/nginx-statefulset nginx=${{ secrets.DOCKER_USERNAME }}/my-nginx:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/nginx-statefulset
